version: "3.8"
services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "4200:5432"
volumes:
  postgres:
